### ISSUE TITLE
App does not handle lists correctly 

### ISSUE THREAD

**Issue by jdh009** [athombv/com.wikipedia#1]
What is your Homey version (Settings → System)?

Homey Firmware Version: 0.8.32

What did you try to achieve?

Please include detailed steps how we can reproduce the issue

Wiki apple or wiki appel 

What was the result?

The list:
Bram Appel (1921-1997), Nederlands voetballer en voetbaltrainer
Karel Appel (1921-2006), Nederlands kunstschilder en beeldhouwer
Maritje Appel (1947), Nederlands burgemeester
René Appel (1945), Nederlands schrijver

sounded like:

Bram Appel (1921-1997), 
Nederlands voetballer en voetbaltrainer Karel Appel (1921-2006)
Nederlands kunstschilder en beeldhouwer Maritje Appel (1947)
Nederlands burgemeester René Appel (1945)
Nederlands schrijver

Due to the missing dots at the end of the lines homey just ignores the end of the line and combines the sentence with the next one. Adding the break in the speech at the place of the comma. Making it sound that Karel Appel is a dutch soccer player and Maritje Apple a famous painter.

**Comment by freekwebdesign** [comment]
Thanks for reporting this issue.
That sounds strange indeed, we will resolve this issue in the next version of the app!

**Comment by Tweake** [comment]
Has been fixed in version 2.0, released in March 2017. In addition it seems that wikipedia no longer presents lists in the format which was causing the issue.
